--1

CREATE OR REPLACE FUNCTION ISNUMBER(MSG IN VARCHAR2)
RETURN VARCHAR2 IS
V_NUM NUMBER;
BEGIN
    V_NUM:=TO_NUMBER(MSG);
    RETURN 'YES';
EXCEPTION
    WHEN VALUE_ERROR THEN RETURN 'NO';
    WHEN OTHERS THEN RETURN 'NO';
END;
/

--2

CREATE OR REPLACE TRIGGER HELLO_WORLD6
AFTER DELETE
ON STUDENTS
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
END;
/ 

--3

CREATE OR REPLACE TRIGGER INVALID_NAME
BEFORE INSERT
ON STUDENTS
FOR EACH ROW
DECLARE
INVALID_NAME EXCEPTION;
CH CHAR(1);
BEGIN
    FOR I IN 1..LENGTH(:NEW.STUDENT_NAME) 
    LOOP
        CH:=SUBSTR(:NEW.STUDENT_NAME,I,1);
        IF NOT ((ASCII(CH) BETWEEN 65 AND 90) OR (ASCII(CH) BETWEEN 97 AND 122)) THEN RAISE INVALID_NAME;
        END IF;
    END LOOP;
EXCEPTION 
    WHEN INVALID_NAME THEN 
    RAISE; --STOPS INSERTION
END;
/

--4

CREATE TABLE LOW_CGPA_STUDENTS(  --ME :)
    STUDENT_NAME VARCHAR2(100)
);

CREATE OR REPLACE TRIGGER FIND_LOW_CGPA
BEFORE INSERT OR UPDATE
OF CGPA
ON STUDENTS
FOR EACH ROW
BEGIN
    IF (:NEW.CGPA<2.0) THEN 
    INSERT INTO LOW_CGPA_STUDENTS VALUES(:NEW.STUDENT_NAME);
    END IF;
END;
/

INSERT INTO STUDENTS VALUES('NMS',1.5);
INSERT INTO STUDENTS VALUES('TNM',3.5);
UPDATE STUDENTS SET CGPA=1.8 WHERE STUDENT_NAME='TNM';
SELECT * FROM LOW_CGPA_STUDENTS;
